### ISSUE TITLE
「Passive Event Listener を使用してサイトでのスクロール パフォーマンスを向上させる」への対応

### ISSUE THREAD

**Issue by technote-space** [yhira/cocoon#16]
# 概要
「onTouchStart」は何か特別な関数ではなく使用できない関数

## 関連
#8 #15 

# 目的
javascript.js の以下のコードですが、
<pre>
document.addEventListener('touchstart', onTouchStart, {passive: true});
</pre>
https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners
への対応として入れてあると思います。  
ちゃんと読んでなかったのでなんでこのコードがあるか理解しておらず、touchイベントが使えるときだけ「onTouchStart」がどこかで定義されて使用可能なのかと勘違いしてそのイベントのチェックだけを追加する[プルリク](https://github.com/yhira/cocoon/pull/5)を投げましたが、そのような特別な関数「onTouchStart」は存在しません。
今もtouch可能な端末（Chromeのエミュレータでも可）から確認するとエラーが発生します #15

> preventDefault() を呼び出さない wheel、mousewheel、touchstart、touchmove のイベントリスナには、すべて passive フラグを追加してください。

とあるように、上記のイベントを設定している箇所すべてで passive: true を追加するのが正しいのだと思います。

> 4. ページとホストが異なるリスナを除外する。

完全にサードパーティー（CDN等のものを使用）のものは除外してチェックされるので問題ありません。
ただ、テーマのpluginsにあるような自サイトでホストしている他のライブラリなどで上記のイベントが passive: true なしで使用されている場合もあるため個別に対応するのは難しいと思います。

# 提案内容
「addEventListener」の動作を上書きして前述のイベントの場合は passive: true を追加してしまうのがよいかもしれません。

**Comment by technote-space** [comment]
すでに #15 をマージされたようですが
<pre>
document.addEventListener('touchstart', onTouchStart, {passive: true});
</pre>
も
<pre>
document.addEventListener('touchstart', function(){}, {passive: true});
</pre>
も意味がないので削除したほうがよいです。

* マージ後の結果
![修正前](https://raw.githubusercontent.com/technote-space/cocoon/images/.github/images/passive-event/before.png)

**Comment by technote-space** [comment]
@yhira 
passive が設定されるようにする修正例です。  
別ファイル化してヘッダーで読み込んでいるため他の点数に影響があると思うので参考程度にしてください。

https://github.com/technote-space/cocoon/commit/8048b203a14d59b5fe34f880bb47971adc0eb854

動作確認
* PC (Windows)
** Chrome (＋スマホエミュ)
** Firefox
** IE
のみ

Todo：スマホの確認等

**Comment by yhira** [comment]
すいません。
GitHubの使い方に慣れていなくてお恥ずかしいのですが、以下の変更点を手元に引っ張ってきてマージする方法とかってあるのでしょうか。
https://github.com/technote-space/cocoon/compare/8ddfd738f20975db49bee434f34e9a5aee5a991b...fdb66ee05d295e7c6452a0e4a8fb123f117b530f
こちらの環境でも、いろいろ動作テストしてみたいと思います。

**Comment by technote-space** [comment]
yhira/cocoon のほうで適当なテスト用のブランチを作成していただければ、そちらにマージさせるプルリクの作成します。
https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/
そのあとはそのブランチでいろいろ確認や調整、問題なければmasterに取り込んでいただくことも可能です。
よろしくお願いいたします。

**Comment by yhira** [comment]
承知しました。
以下のブランチを作成しプッシュしておきました。
https://github.com/yhira/cocoon/tree/Passive_Event_Listener

**Comment by technote-space** [comment]
プルリクエストを作成しました。  
取り込んで色々試していただければと

**Comment by technote-space** [comment]
マージありがとうございます。
クローズします。
