### ISSUE TITLE
キャッシュ削除が正しく実行されない場合がある

### ISSUE THREAD

**Issue by technote-space** [yhira/cocoon#23]
# バグの概要

「全てのキャッシュの削除」などで一部のキャッシュが削除されない場合がある。

# 再現手順

1. SNSのキャッシュがない状態にしておく
2. ブログカードのキャッシュがある状態にしておく
3. 『全てのキャッシュ削除』を押下
4. ブログカードのキャッシュが残ったまま

# 期待する動作

キャッシュが削除されること

# スクリーンショット

* 『全てのキャッシュ削除』押下前
![before](https://raw.githubusercontent.com/technote-space/cocoon/images/.github/images/delete-cache/before.png)
* 『全てのキャッシュ削除』押下後（何回押しても消えない）
![after](https://raw.githubusercontent.com/technote-space/cocoon/images/.github/images/delete-cache/after.png)

# バグが発生した環境
* WordPressのバージョン
  * v5.0.2
* テーマのバージョン
  * v1.5.2.3

# 補足

```
  return delete_sns_count_caches() &&
         delete_popular_entries_caches() &&
         delete_blogcard_caches() &&
         delete_amazon_api_caches() &&
         delete_amp_caches();
```
のように&&になっているため前がfalseの場合後のほうが実行されません。
delete_sns_count_cachesなどはDELETEが実行されその結果（rows_affected）が返り値であるため、０件の場合はそのあとの削除が実行されません。

**Comment by yhira** [comment]
確かに。０件の場合は、考えてませんでした。
マージして試してみようと思います。

**Comment by yhira** [comment]
動作確認したところ、うまく削除できました。
ありがとうございます！

動作確認中、全てのキャッシュの削除に、僕の書き忘れで楽天APIの分が含まれていなかったので追加しました^^;
https://github.com/yhira/cocoon/commit/2dc964b4ef1b633da62f367c56eff041e4e9e714
おかげで気づくことができました。

**Comment by technote-space** [comment]
対応ありがとうございました。クローズします。
