### ISSUE TITLE
印刷イメージを画面表示のビジュアルに合わせる機能が欲しい

### ISSUE THREAD

**Issue by katahiromz** [yhira/cocoon#26]
いくつかのブラウザの印刷において、長いパラグラフが折り返されないなどの問題があります。印刷イメージを画面表示のビジュアルに合わせる機能があれば助かります。

**Comment by katahiromz** [comment]
https://blog.nosehiroyuki.com/wordpress-print/
これは参考になりませんかねえ。

**Comment by yhira** [comment]
はみ出すというのはどういった状態でしょう？
よろしければ、以下のような感じでキャプチャをアップしていただいてよろしいでしょうか。
![2019-09-06_23h40_51](https://user-images.githubusercontent.com/1787429/64436789-08d6a280-d100-11e9-8a14-3e96cb7047e0.png)

**Comment by katahiromz** [comment]
![plast](https://user-images.githubusercontent.com/2107452/64437587-7f27d480-d101-11e9-83a5-974bef90eaf2.png)
「縮小して全体を表示する」を「100%」に変えると長い文章（パラグラフ）が切れます。

**Comment by yhira** [comment]
一応、修正を試みたものをアップしておきました。
![2019-09-07_00h40_55](https://user-images.githubusercontent.com/1787429/64476150-5d445580-d1c6-11e9-8d6a-f522f7af7eba.png)

**Comment by katahiromz** [comment]
印刷でパラグラフが折り返されるようになりました。ありがとうございます。

テーブル（table）の幅についても同じように設定してくれると助かります。
