### ISSUE TITLE
Firefoxで縦に長いページを印刷すると2ページ以降が正しく印刷されない

### ISSUE THREAD

**Issue by katahiromz** [yhira/cocoon#27]
Firefoxで縦に長いページを印刷すると、印刷イメージの2ページ以降が空白になってしまいます。

![page](https://user-images.githubusercontent.com/2107452/64512830-2e42f680-d322-11e9-813d-62cb232aafdd.png)

**Comment by katahiromz** [comment]
https://github.com/yoshiko-pg/your-name/issues/6

**Comment by yhira** [comment]
一応、修正してみました。
原因はこれっぽいです。
https://github.com/yoshiko-pg/your-name/issues/6

**Comment by katahiromz** [comment]
![page](https://user-images.githubusercontent.com/2107452/64535256-e4720480-d351-11e9-99c4-5d8ff7398beb.png)
すみませんが、まだ直っていないように思われます。キャッシュを削除して試してみたのですが。

**Comment by yhira** [comment]
僕の環境だと、こんな感じで表示されているようです。
![2019-09-09_23h00_32](https://user-images.githubusercontent.com/1787429/64537440-cad2bc00-d355-11e9-82c9-2bc63a7841e7.png)
その後、管理者用のPVとか表示されているバーも非表示にしたので、もう一度アップデートしてみていただけますか。

**Comment by katahiromz** [comment]
ああ、最新のものは自動更新にはなっていないんですね。明日、アップデート試してみます。

**Comment by katahiromz** [comment]
まだ直っていません。

**Comment by yhira** [comment]
GitHubに書かれているので、GitHubのファイルで更新されているのかと思っていました。
こちらのページのダウンロードボタンのファイルが最も新しいものになります。
https://github.com/yhira/cocoon

**Comment by katahiromz** [comment]
解決しました。ありがとうございます！
