### ISSUE TITLE
Internet Explorerの印刷でコンテンツの背景がおかしい

### ISSUE THREAD

**Issue by katahiromz** [yhira/cocoon#29]
１．Internet Explorerで次のページを開きます。https://****.com/wp/
２．左上の歯車をクリックして、「印刷」→「印刷プレビュー」を選びます。
３．「印刷プレビュー」が表示されたら、歯車をクリックします。
４．「ページ設定」が表示されます。ここで「背景の色とイメージを印刷する」にチェックを入れます。
５．「OK」をクリックします。
６．コンテンツの背景がおかしくなります。

![印刷プレビュー](https://user-images.githubusercontent.com/2107452/65303408-f0af5a80-dbb8-11e9-9dc6-dacf03633f26.png)

**Comment by yhira** [comment]
詳しい再現方法ありがとうございます。
こちらのように修正してみました。
https://github.com/yhira/cocoon/commit/bbe24bf484c7045eb86168739bb0b6123617ba00

**Comment by katahiromz** [comment]
問題は解決しました。ありがとうございます。
