### ISSUE TITLE
Internet Explorerで画像のキャプションがおかしい

### ISSUE THREAD

**Issue by katahiromz** [yhira/cocoon#30]
１．Internet Explorerで次のページを開きます。https://****.com/wp/2019/09/04/plast/
２．画像のキャプションの「セメント汚水処理」が縦書きになってしまいます。
![セメント汚水処理](https://user-images.githubusercontent.com/2107452/65303708-aed2e400-dbb9-11e9-915f-754358627860.png)

**Comment by yhira** [comment]
こちらのように修正してみました。
https://github.com/yhira/cocoon/commit/a0e7eb940398abebd1ca46d38a8c841e8b32cffe

**Comment by katahiromz** [comment]
問題は解決しました。ありがとうございます。
