### ISSUE TITLE
テーブルについて

### ISSUE THREAD

**Issue by katahiromz** [yhira/cocoon#31]
テーブルについて。少し難しいかもしれませんが。

セル見出し（＜TH＞...＜/TH＞）と折り返しなし（＜NOBR＞...＜/NOBR＞）に対応して頂けると助かります。

テーブルの中の画像（＜IMG＞）、テーブルの中のリスト（＜UL＞,＜OL＞,＜LI＞）にも対応していただけませんか？

よろしくお願いいたします。

**Comment by yhira** [comment]
現在書かれたタグを利用するとどのようになるのでしょうか？
キャプチャー等を見せていただければと思います。
書かれている内容だけだと、どんな問題が出ているのかちょっとわからないので。
ただ、thとかは普通に使えたと思うのですが。実際僕も使っています。

**Comment by yhira** [comment]
もし不具合が出るソースコードがあるのであれば、そのソースコードも貼り付けていただければ、それで動作確認いたします。

**Comment by katahiromz** [comment]
![image](https://user-images.githubusercontent.com/2107452/65406737-69adec80-de1b-11e9-9066-898b306c6f08.png)
ビジュアル編集だと、テーブル内のリストが一行のみになります。
```html
<table class="wp-block-table alignfull"><tbody><tr><th>社名</th><td>株式会社エコサイエンス</td></tr><tr><th>設立</th><td>平成19年6月13日</td></tr><tr><th>所在地</th><td>〒880-0924 宮崎県宮崎市郡司分甲129-1-3</td></tr><tr><th><nobr>事業内容</nobr></th><td><ol><li>無機系凝集剤の製造及び販売</li><li>無機性・有機性の汚濁水処理施設に対応できる環境機器の製造及び販売並びにこれらに関するコンサルタント業</li><li>前各号に附帯する一切の業務</li></ol></td></tr><tr><th>TEL</th><td><a href="tel:0985-65-3009">0985-65-3009</a></td></tr><tr><th>FAX</th><td>0985-65-3090</td></tr><tr><th><nobr>ホームページ</nobr></th><td><a href="https://ecosci2008.com">https://ecosci2008.com</a></td></tr><tr><th><nobr>メールアドレス</nobr></th><td><a href="mailto:plast@ecosci2008.com">plast@ecosci2008.com</a></td></tr></tbody></table>
```

**Comment by katahiromz** [comment]
ビジュアル編集だと＜TH＞を指定する方法がなかったように思われます。

**Comment by yhira** [comment]
ビジュアル編集というのは、ビジュアルエディター（旧エディター）での編集でしょうか．それともブロックエディターでの編集でしょうか。
いずれにせよ、WordPressデフォルトの機能ではそういった機能はないかと思います。
ソースコードで編集するか、プラグインか何かで対応していただくしかないかもしれません。

**Comment by katahiromz** [comment]
わかりました。
