### ISSUE TITLE
Google Analytics のコードを選択できるようにしたい

### ISSUE THREAD

**Issue by ress997** [yhira/cocoon#32]
https://github.com/jehna/ga-lite はコードを含めたりCDNを使用しキャッシュ可能で `Do not track` に対応しています。
PageSpeed Insights においてより100点に近づけることができるので採用してほしいです。

実際にはタイトルのようにこのコードとanalytics.jsを選択できたらいいと思います

**Comment by yhira** [comment]
コレって、Google Analyticsのコードを以下に変更すれば良いだけなんですかね？

```
<script>
(function(e,t,n,i,s,a,c){e[n]=e[n]||function(){(e[n].q=e[n].q||[]).push(arguments)}
;a=t.createElement(i);c=t.getElementsByTagName(i)[0];a.async=true;a.src=s
;c.parentNode.insertBefore(a,c)
})(window,document,"galite","script","https://cdn.jsdelivr.net/npm/ga-lite@2/dist/ga-lite.min.js");

galite('create', 'UA-XXXXXXXX-X', 'auto');
galite('send', 'pageview');
</script>
```

使ってみられたことはありますか？

**Comment by ress997** [comment]
README.md に書いてあるコードで動きますよ

私が管理しているサイトで一部適用してみたところ、今まで広告ブロックに引っかかり計測されてなかったのユーザーも計測されました。

PageSpeed Insights において analytics.js を除くと100点になるサイトも満点になりいいと思いますよ

**Comment by yhira** [comment]
承知しました。
ただ今は、v2.0.0直前で、ちょっと立て込んでいてすぐには実装できないかもしれません。
v2.0.0公開後しばらくして落ち着いたら、実装できればなと思います。
落ち着いた状態でアップデートして様々な方の影響を見たいので。

あとこれのGoogleタグマネージャ版はないものかとgtm-liteと検索して見たのですが、ないっぽいですね。

**Comment by ress997** [comment]
わかりました、楽しみに待っています。

google tag manager lite については私も欲しいと覆って調べてみたが存在していないみたいですね

**Comment by yhira** [comment]
ようやくCocoon2.0を公開できたので、ga-liteを適用させてみました。
https://github.com/yhira/cocoon/commit/19d650bd924699307374a2343a0d6120a0b13301
動作確認してみた限りでは、問題なく動作しているようです。

**Comment by ress997** [comment]
https://wp-cocoon.com/2-0-1/ 早速アップデートし使用できることを確認しました。

記事に書かれている通り完全互換性は無いですが ga-lite でも十分な内容もあるためありがたいアップデートです。
スコアやただ計測入れてみたい程度の方には十分だと思います。
これからも開発頑張ってください！
