### ISSUE TITLE
画像のキャプションが中央ぞろえにならない

### ISSUE THREAD

**Issue by katahiromz** [yhira/cocoon#33]
https://ecosci2008.com/wp/2019/10/08/%e3%83%86%e3%82%b9%e3%83%88%e3%83%9a%e3%83%bc%e3%82%b8/

![cap](https://user-images.githubusercontent.com/2107452/69116138-90f90100-0ace-11ea-93fe-b4531f4e5c70.png)

画像のキャプションが中央ぞろえになりません。対応をお願いします。

**Comment by yhira** [comment]
wp-block-imageは、WordPressデフォルトのブロックなので、元々そういう仕様なんだと思います。

**Comment by katahiromz** [comment]
カスタマイズで直すことにします。ありがとうございました。
