### ISSUE TITLE
コメント欄をシンプルスレッドにした場合、comment-reply.js が機能しない

### ISSUE THREAD

**Issue by tsukumijima** [yhira/cocoon#42]
いつも使わせていただいています。ありがとうございます。

さて、Cocoon 設定からコメントタイプを「シンプルスレッド」にした場合、コメントの返信をリロードなしで行えるようにする comment-reply.js（実際に読み込まれるのは comment-reply.min.js ）が機能しなくなります。
原因はコメントタイプ「シンプルスレッド」に設定すると各コメントの HTML の ID が div-comment-(数字) から st-comment-(数字) に変更されるのに、返信ボタン内の data-belowelement 属性（返信ボタンに紐付いているコメントの ID を示す属性らしい）が div-comment-(数字) のままになっているためのようです。
返信ボタンを押すと返信ボタンに紐づくコメントが取得できないため comment-reply.js が働かず、一度リロードされてからコメント欄に遷移するような状況になってしまっています（本来はコメントの真下にコメント欄が来る）。
コメントタイプを「デフォルト」に設定すると上記の問題は発生しなくなります。

今までは comment-reply.js の 312 行目を var addBelowElement = getElementById( addBelowId.replace('div-', 'st-') ); に変更することでどうにかしてきましたが、WordPress 本体をアップデートすると修正し直しになってしまい面倒です。
ぜひ修正していただければと思います。よろしくお願いします。

![615](https://user-images.githubusercontent.com/39271166/92410439-05488200-f17f-11ea-909e-3986474170f9.png)

**Comment by yhira** [comment]
詳細なご連絡ありがとうございます！
HTML IDの「div-comment-(数字)」は変更してはいけないものだったっぽいですね。
幸い、「st-comment-(数字)」で指定しているスタイルもないのでdivに戻しておくことにしました。
以下のように修正いたしました。
https://github.com/yhira/cocoon/commit/510e206a7251eecf24f2cde31268bff1686b9da6

**Comment by tsukumijima** [comment]
修正ありがとうございます！！
まだ試せていませんが、大丈夫そうなので一旦閉じさせていただきます。

**Comment by tsukumijima** [comment]
先ほどアップデートを適用したところ、直っていることを確認できました。
ありがとうございました！
