### ISSUE TITLE
NO IMAGE画像が反映されない（img src=が空になる）

### ISSUE THREAD

**Issue by tsukumijima** [yhira/cocoon#43]
お世話になっています。

さて、Cocoon 設定の [画像] にある NO IMAGE画像の設定が、最近表示されなくなってしまいました。
そのため、記事一覧ページのサムネイルが、記事内に画像がない記事のみ表示されない感じになってしまっています。

具体的には、HTML 側で img#.no-image.entry-card-thumb-image.list-no-image の要素の src が空 (unknown) になっており、画像自体が設定されていない感じです。
NO IMAGE画像は既に設定されている状態で、一度クリアしてもう一度設定したりも試してみましたが、変わらず同じ状況でした。また、設定をクリアした状態だと確か「NO IMAGE」と書かれた Cocoon 備え付けの代替画像が表示されるようになっていたはずですが、それも表示されません。
ここ数ヶ月設定はいじっていないはずなので、（おま環かもしれませんが）もしかすると最近のアップデートで新たに起きた不具合かもしれないなーと思い、報告させていただきました。
（ただし、ブログはかれこれ1年以上運営しているので、DB の構造が古い・他の設定と競合している・プラグインのせいなど、他の所に原因がある可能性もあります）

もし Cocoon 側の不具合であれば修正していただけると助かります。よろしくお願いします。

<img width="1440" src="https://user-images.githubusercontent.com/39271166/93985105-9a728a00-fdbf-11ea-9b1e-b772ac95a1ed.png">

**Comment by tsukumijima** [comment]
先程更新したところ、NO IMAGE 画像が正しく表示されるようになりました！
いまいち原因がわからずじまいですが、解決したため閉じさせていただきます。お騒がせしました…

**Comment by yhira** [comment]
それは、最新版で不具合が修正されたからだと思います。
Cocoonサイトのフォーラムに同様の不具合が報告され、修正してバージョンアップしました。
https://wp-cocoon.com/community/postid/39946/

**Comment by tsukumijima** [comment]
そうでしたか！
迅速な修正ありがとうございました！
