### ISSUE TITLE
ko.po  ファイルが正しくないようです。

### ISSUE THREAD

**Issue by semicolon3253** [yhira/cocoon#45]
このテーマをダウンロードした後、韓国語を適用しましたが、いくつかのテキストが翻訳されませんでした。
それで、ko.poファイルを開いてみたら、いくつかの文字列の経路が間違っていることが分かりました。

例えば、msgidが「トップ」の場合は経路が「lib/page-settings/ads-forms.php:149」になっていますが、実際そこにはありません。
経路が正しくありません。

しかし、en.po  ファイルは経路はすべて一致します。
これを修正できますか。それとも私が修正できる方法がありますか。

**Comment by yhira** [comment]
ko.poファイルは古い行数（経路は違う）にはなっているかもしれません。
ただ、それと韓国語翻訳が出ないのは、別の話だったりします。
というのも、僕自身韓国語は全くわからないので翻訳は全く行っていないからです^^;

ただ、経路が違うのは、こちら側でko.poファイルを更新することで修正できるので、新しい状態に更新しておきました。
https://github.com/yhira/cocoon/commit/dfc864f5954e4d7d7129051fea9b9dc3e393f106
こちらなどで書かれているPoeditと言うツールを利用することで、自前でも修正したり編集したりすることもできます。
https://github.com/yhira/cocoon/pull/44
