### ISSUE TITLE
「アイキャッチ自動設定を有効にする」の設定が OGP に適切に処理されていない

### ISSUE THREAD

**Issue by mirumirumi** [yhira/cocoon#66]
わいひらさん、お久しぶりです。

投稿内に画像が存在する場合にアイキャッチを自動設定する Cocoon の設定がありますが、これが OGP 側の設定反映で意図しない挙動になっていると思われます。

投稿としてはアイキャッチを設定していない状態で、これは記事の表示的にも正しく処理されますが、OGP では NO_IMAGE 用の画像ではなく投稿内の先頭に登場する画像が選択されています。

「アイキャッチ自動設定を有効にする」の設定は OGP の反映にも同期するのが感覚的に自然だと思うのですが、いかがでしょうか。

一応 PR も作成したのでご確認いただけますと幸いです。

**Comment by yhira** [comment]
書き込みに気づかず返信が遅れました。
恐れ入りますが、一点確認させてください。

> 投稿としてはアイキャッチを設定していない状態で、これは記事の表示的にも正しく処理されますが、OGP では NO_IMAGE 用の画像ではなく投稿内の先頭に登場する画像が選択されています。

こちら、 OGP画像では本文先頭の画像になるとのことですが、アイキャッチ自動選択側だと何が選択されていますでしょうか。NO_IMAGEということでよろしいでしょうか。

**Comment by mirumirumi** [comment]
すれ違いを避けるため、関連する設定内容をスクリーンショットで掲載いたします。

## **Cocoon設定「画像」：**
![2022-02-01_14h08_28](https://user-images.githubusercontent.com/88871226/151915699-8e1461a6-0d82-425b-b21b-357aee98611d.png)

## **Cocoon設定「画像 → NO IMAGE」（OGPで期待する出力画像）：**
![2022-02-01_14h09_46](https://user-images.githubusercontent.com/88871226/151915824-ccbf728c-dbd3-4250-bd7a-2d111894beef.png)

## **該当記事のアイキャッチ設定（未設定状態）：**
![2022-02-01_14h10_53](https://user-images.githubusercontent.com/88871226/151915893-152fc8cf-212b-4647-b9a2-499988697ed0.png)

## **実際に出力されているOGP画像（記事最初の投稿画像）：**
![2022-02-01_14h12_58](https://user-images.githubusercontent.com/88871226/151916104-54879b68-35ba-405b-8477-021f64267abf.png)

（該当記事URLは https://mirumi.me/tech/231/ ですが、今は自分で修正してしまっているのでOGP出力は正しい状態です）


ご質問の返答になっているでしょうか。

**Comment by yhira** [comment]
画像にあるように「アイキャッチ自動設定を有効にする」が無効の状態では、OGPは意図した動作のように見えます。

> Cocoon設定「画像 → NO IMAGE」（OGPで期待する出力画像）：

こちらは、NO IMAGE画像なので、OGPで積極的に採用する画像になるようには設定していません。

「アイキャッチ自動設定を有効にする」が無効になっているときのOGP動作としては意図したとおりではあります。
今回の問題としては「アイキャッチ自動設定を有効にする」が有効になっている時、意図した画像が選択されないということではないのでしょうか。

もし僕がみるみさんの意図すること僕が理解できていないのでしたら申し訳ないです。

**Comment by mirumirumi** [comment]
なるほど、「アイキャッチと OGP の設定はあくまでも別々である」というお考えですね。
一番最初に申し上げた通り、ここが同期していないのが自然ではないかな？というのが僕の打ち上げでしたので、そうではないというわいひらさんのお考えを聞けてちゃんと納得できました。

例によって自分でカスタマイズを加えることにいたします！

（PR もクローズしてきます、お手数おかけいたしました）

**Comment by yhira** [comment]
> なるほど、「アイキャッチと OGP の設定はあくまでも別々である」というお考えですね。
> 一番最初に申し上げた通り、ここが同期していないのが自然ではないかな？というのが僕の打ち上げでしたので、そうではないというわいひらさんのお考えを聞けてちゃんと納得できました。

いえ、そうではなくて「アイキャッチの自動設定」が無効になっているのに同期というのはどういうことなんだろう？と思いました。

Cocoon設定で「アイキャッチの自動設定」が有効になっていて、「OGP設定画像」と「自動選択で選ばれるアイキャッチ画像」が違うというのならわかるんです。

でもスクリーンショットにもあるように無効になっているのに、同期とは？と思ったんです。
https://user-images.githubusercontent.com/88871226/151915699-8e1461a6-0d82-425b-b21b-357aee98611d.png

なので自分でもいまいち理解できていないのかもと思い以下のように先日書きました。

> もし僕がみるみさんの意図すること僕が理解できていないのでしたら申し訳ないです。

**Comment by mirumirumi** [comment]
> Cocoon設定で「アイキャッチの自動設定」が有効になっていて、「OGP設定画像」と「自動選択で選ばれるアイキャッチ画像」が違うというのならわかるんです。

記事にアイキャッチが指定されていなくて、かつ「アイキャッチの自動設定」が無効なら一般的には常に NO_IMAGE が使用されると考えると思うのですが、そうなると当然 OGP の出力画像も同じ状態（＝NO_IMAGE）になることを想像しませんか？という意味です。

意志を持って「アイキャッチの自動設定」をオフにしているユーザーは、おそらく OGP の出力画像でも記事最初の画像の自動選択をしてほしくないと考えるのではないでしょうか、といえば伝わりますでしょうか。

それに対してのわいひらさんのお返事を拝見した僕は、「アイキャッチと OGP は独立したものということだからこの指摘はズレているのだな」と理解したということになります。

**Comment by yhira** [comment]
そういうことですか。冒頭の書き込みに同期とあったのでアイキャッチ自動設定が有効な時にOGPと合わないということかと思っていました。

SNSに出るOGP設定は、「少しでも記事の内容にそうものが出るように」とそのような仕様になっています。
アイキャッチ自動設定が無効の時は、アイキャッチは自前で選択するものと思っていたので、そこを合わせるという発想はなかったです。

アイキャッチ自動設定が無効の時OGP画像は、僕の考えとしては「少しでも記事の内容にそうもの」。みるみさんとしては「NOイメージ画像」を出力したいということだったんですね。

> 意志を持って「アイキャッチの自動設定」をオフにしているユーザーは、おそらく OGP の出力画像でも記事最初の画像の自動選択をしてほしくないと考えるのではないでしょうか、といえば伝わりますでしょうか。

「アイキャッチの自動設定」機能自体デフォルトで無効なのでそこまで意思をもって無効にしておられる方は少ないものと思っていました。
「アイキャッチの自動設定」自体は、Auto Post Thumbnailというプラグインからっており、その機能自体アイキャッチを設定するのが面倒な人が、とりあえずアイキャッチを設定しないで投稿したら「最初の画像」が選択される機能だったので、OGP画像もその仕様に合わせるようにした感じです。
「アイキャッチの自動設定」が無効の時のことまでは正直考えてなかったですね。

僕はそういった状況になったことはないので、ここはそういう状況をになったことのある方の意見を尊重して、テスト的にマージするというのも全然ありだと思います（意図がわからないうちはマージできませんでした。今回遅ればせながらようやく意図がわかりました^^;）。
ただ、「アイキャッチの自動設定」について意識しないで使っている方で、アイキャッチなしで投稿したらOGP画像に「投稿の最初の画像」が出ることを期待して利用している方がいて、問い合わせが多々来たら戻す可能性もあるかもしれません。

**Comment by mirumirumi** [comment]
ご丁寧に最後までお付き合いいただきいつもありがとうございます…！

> アイキャッチ自動設定が無効の時OGP画像は、僕の考えとしては「少しでも記事の内容にそうもの」。みるみさんとしては「NOイメージ画像」を出力したいということだったんですね。

そういうことになりますね。

> 「アイキャッチの自動設定」機能自体デフォルトで無効なのでそこまで意思をもって無効にしておられる方は少ないものと思っていました。

これも言われてみればそうでした。だからこそ稀なパターンということで条件分岐に漏れがあったのかな？と感じた次第です（もちろん今ではそうではないと理解できましたが！）。

「アイキャッチ自体は設定しないのに OGP は全部ちゃんと統一したい」という今回の僕の要望は、珍しく思えるかもしれませんが意外とあるのではと思います。今回の話は技術ブログで考えていることですが、テクノロジーメインでテキスト主体だから毎度のアイキャッチはいらない、でも SNS でシェアされたときにサイトの統一感として OGP は揃えたい、みたいなことですね。

> 僕はそういった状況になったことはないので、ここはそういう状況をになったことのある方の意見を尊重して、テスト的にマージするというのも全然ありだと思います

これはとても嬉しいです！
変更点も少ないので、問題あればすぐに戻せますしね。

> 「アイキャッチの自動設定」について意識しないで使っている方で、アイキャッチなしで投稿したらOGP画像に「投稿の最初の画像」が出ることを期待して利用している方がいて、問い合わせが多々来たら

僕もこの問題は気にしていました。
設定は変えていないのにいきなり挙動が変わってしまうのでもしかしたらたくさんフォーラムに来てしまうかもですね…😅

**Comment by yhira** [comment]
> 「アイキャッチ自体は設定しないのに OGP は全部ちゃんと統一したい」という今回の僕の要望は、珍しく思えるかもしれませんが意外とあるのではと思います。今回の話は技術ブログで考えていることですが、テクノロジーメインでテキスト主体だから毎度のアイキャッチはいらない、でも SNS でシェアされたときにサイトの統一感として OGP は揃えたい、みたいなことですね。

あー、これは確かに。
Cocoonは、結構テクノロジー系のブログで使われていて、そういったブログは結構アイキャッチを設定して使わないんですよね。

> 僕もこの問題は気にしていました。
> 設定は変えていないのにいきなり挙動が変わってしまうのでもしかしたらたくさんフォーラムに来てしまうかもですね…sweat_smile

双方それぞれ、おられるとは思いますが、一旦マージしてみましょう。ダメなら戻せばいいんだから。
とりあえず、Reopenしてマージしてみます。Reopenは初めて使うので、合っているのかどうかわからないのですが、このあとちょっと試してみます。
